import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#b7d23d',
        'inverse-on-surface': '#2a313a',
        'surface-dim': '#0d141c',
        secondary: '#dbb8ff',
        primary: '#d3ef57',
        'on-secondary-fixed': '#2b0052',
        'on-tertiary': '#003829',
        error: '#ffb4ab',
        outline: '#90937d',
        'surface-container': '#192028',
        'tertiary-fixed-dim': '#54ddb0',
        'primary-container': '#d3ef57',
        'outline-variant': '#454836',
        'tertiary-container': '#74facb',
        'on-tertiary-fixed': '#002116',
        tertiary: '#ffffff',
        'secondary-fixed': '#efdbff',
        'inverse-primary': '#556500',
        background: '#0d141c',
        'on-secondary': '#470083',
        'primary-fixed-dim': '#b7d23d',
        'on-primary-fixed': '#181e00',
        'surface-container-highest': '#2e353e',
        'on-error': '#690005',
        'secondary-container': '#6327a1',
        'surface-container-high': '#242b33',
        'primary-fixed': '#d3ef57',
        'on-error-container': '#ffdad6',
        surface: '#0d141c',
        'on-tertiary-container': '#007256',
        'on-surface-variant': '#c6c8b0',
        'surface-container-low': '#151c24',
        'on-background': '#dce3ee',
        'on-primary-container': '#5a6b00',
        'surface-container-lowest': '#080f16',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#dbb8ff',
        'on-secondary-container': '#d1a6ff',
        'on-secondary-fixed-variant': '#60249e',
        'surface-bright': '#333a43',
        'inverse-surface': '#dce3ee',
        'on-surface': '#dce3ee',
        'on-primary-fixed-variant': '#3f4c00',
        'on-tertiary-fixed-variant': '#00513c',
        'on-primary': '#2b3400',
        'tertiary-fixed': '#74facb',
        'surface-variant': '#2e353e',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
        mono: ['Geist Mono', 'monospace'],
        pixel: ['Geist Pixel', 'monospace'],
      },
    },
  },
  plugins: [],
}

export default config
